"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import data from './pilot.json';
import './knowledge.css';
import {straightLayout} from './straight-layout';
import preparedLayouts from './layouts.json';
import {PlacesOfActivity} from '@/components/map/PlacesOfActivity';
const names:Record<string,string>={teacher_student:'מסירת תורה / רב ותלמיד',parent_child:'הורה וילד',spouse:'בני זוג',sibling:'אחים',bar_plugta:'חברותא'};
const colors:Record<string,string>={teacher_student:'#53665a',parent_child:'#8c9086',spouse:'#a58379',sibling:'#92917a',bar_plugta:'#c09b4f'};
type Point={x:number;y:number};

const knowledge=new Map(data.people.map(p=>{const refs=new Set([...(p.summary?.citations||[]),...p.teachings.map(t=>t.citation),...p.facts.flatMap(f=>f.citations),...data.edges.filter(e=>e.a===p.id||e.b===p.id).flatMap(e=>e.citations)]);return[p.id,refs.size];}));
const radius=(id:string)=>20+Math.min(16,Math.sqrt(knowledge.get(id)||0)*4);
const initials=(name:string)=>name.replace(/^(רבי|רבן|רב) /,'').split(' ').slice(0,2).map(n=>n[0]).join('');
type Layout=ReturnType<typeof straightLayout>;
type StoredLayout=Omit<Layout,'positions'|'anchors'> & {positions:[string,Layout['positions'] extends Map<string,infer P>?P:never][];anchors:[string,string][]};
const stored=preparedLayouts as unknown as Record<string,StoredLayout>;
const layoutCache=new Map<string,Layout>();
function getLayout(people:typeof data.people,edges:typeof data.edges){const key=people.map(p=>p.id).join(',')+'|'+edges.map(e=>e.id).join(',');let result=layoutCache.get(key);if(!result){const saved=stored[key];result=saved?{...saved,positions:new Map(saved.positions),anchors:new Map(saved.anchors)}:straightLayout(people,edges,data.edges);if(layoutCache.size>24)layoutCache.clear();layoutCache.set(key,result);}return result;}
function straightPath(a:Point,b:Point,ra:number,rb:number){const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);return `M ${a.x+dx*ra/d} ${a.y+dy*ra/d} L ${b.x-dx*rb/d} ${b.y-dy*rb/d}`;}
export default function KnowledgeGraph(){
 const [selected,setSelected]=useState<string|null>(null),[edgeId,setEdgeId]=useState<string|null>(null),[query,setQuery]=useState(''),[family,setFamily]=useState('teacher_student'),[scope,setScope]=useState('all'),[certain,setCertain]=useState(false),[local,setLocal]=useState(false),[view,setView]=useState({x:0,y:-270,z:1});
 const [fullscreen,setFullscreen]=useState(false);
 useEffect(()=>{if(!fullscreen)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[fullscreen]);
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{id:number;p:Point;view:typeof view;moved:boolean}|null>(null);
 useEffect(()=>{const el=svg.current;if(!el)return;const preventScroll=(e:WheelEvent)=>e.preventDefault();el.addEventListener('wheel',preventScroll,{passive:false});return()=>el.removeEventListener('wheel',preventScroll);},[]);
 const basePeople=useMemo(()=>data.people.filter(p=>(scope==='all'||(scope==='review'?p.review:p.group===scope))),[scope]);
 const baseIds=new Set(basePeople.map(p=>p.id));
 const filteredEdges=data.edges.filter(e=>baseIds.has(e.a)&&baseIds.has(e.b)&&(family==='all'||e.family===family)&&(!certain||e.state==='known'));
 const neighbors=new Set<string>(selected?[selected]:[]);filteredEdges.forEach(e=>{if(e.a===selected)neighbors.add(e.b);if(e.b===selected)neighbors.add(e.a);});
 const visible=basePeople.filter(p=>!local||!selected||neighbors.has(p.id)),ids=new Set(visible.map(p=>p.id)),edges=filteredEdges.filter(e=>ids.has(e.a)&&ids.has(e.b));
 const graph=getLayout(visible,edges),positions=graph.positions;
 const person=data.people.find(p=>p.id===selected),edge=data.edges.find(e=>e.id===edgeId),relations=data.edges.filter(e=>e.a===selected||e.b===selected);
 const teachers=relations.filter(e=>e.family==='teacher_student'&&e.b===selected),students=relations.filter(e=>e.family==='teacher_student'&&e.a===selected),otherRelations=relations.filter(e=>e.family!=='teacher_student');
 const searchPeople=basePeople.filter(p=>p.name.includes(query.trim()));
 function clear(){setSelected(null);setEdgeId(null);setLocal(false);}
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setFullscreen(false);setSelected(null);setEdgeId(null);setLocal(false);setQuery('');}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
 function choose(id:string){setQuery('');setSelected(id);setEdgeId(null);const p=positions.get(id);if(p)setView(v=>({...v,x:-p.x*v.z,y:-p.y*v.z}));}
 const initialFocus=useRef(false);
 useEffect(()=>{if(initialFocus.current)return;initialFocus.current=true;const id=new URLSearchParams(window.location.search).get('person');if(!id||!data.people.some(p=>p.id===id))return;const p=positions.get(id);setSelected(id);if(p)setView(v=>({...v,x:-p.x*v.z,y:-p.y*v.z}));},[positions]);
 function jump(period:string){const band=graph.bands.find(b=>b.id===period);if(!band)return;clear();setView({x:0,y:-(band.y+80)-270,z:1});}
 function fit(){setLocal(false);setSelected(null);setEdgeId(null);const z=Math.min(1,1100/graph.width,740/graph.height);setView({x:0,y:-(graph.height/2-80)*z,z});}
 function sourceList(refs:string[]){return [...new Set(refs)].map(id=>{const c=data.citations.find(c=>c.id===id);return c?<details key={id} className="kg-source"><summary>{c.label}</summary>{c.text?<p>{c.text}</p>:<p>אפשר לעיין במקור ובהקשר המלא בקישור.</p>}<small>{c.edition} · {c.license}</small><a href={c.url} target="_blank" rel="noopener noreferrer">פתיחת המקור ↗</a></details>:null;});}
 function relationList(rows:typeof data.edges,empty:string){return rows.length?rows.map(e=><div className="kg-relation" key={e.id}><button onClick={()=>choose(e.a===selected?e.b:e.a)}>{data.people.find(p=>p.id===(e.a===selected?e.b:e.a))?.name}</button><button onClick={()=>setEdgeId(e.id)}><small>{e.state==='known'?'מבוסס במקור':'לבירור'} · מקורות ←</small></button></div>):<p className="kg-muted">{empty}</p>;}
 function zoom(f:number){setView(v=>{const z=Math.max(.08,Math.min(4,v.z*f));return{x:v.x*z/v.z,y:v.y*z/v.z,z};});}
 return <section className={fullscreen?"kg kg-fullscreen":"kg"} dir="rtl"><div className="kg-top"><div><span className="kg-eyebrow">תולדות / פרקי אבות א–ו</span><h1>עץ מסירת התורה</h1></div><div className="kg-count"><b>{visible.length}</b> רשומות <span>·</span> <b>{edges.length}</b> קשרים</div>{selected&&<button onClick={clear}>ביטול בחירה ×</button>}<button aria-pressed={fullscreen} onClick={()=>setFullscreen(v=>!v)}>{fullscreen?"יציאה ממסך מלא ✕":"מסך מלא ⛶"}</button><button onClick={fit}>התאמה למסך ↗</button></div><div className="kg-notice">טיוטת מחקר · כל חכמי הפיילוט מוצגים לפי תקופה, גם כשאין להם קשר מסירה מתועד. הסדר האנכי נקבע לפי תקופות מתועדות; החצים מציגים מי קיבל ממי. תקופות פעילות עשויות לחפוף. גודל העיגול משקף מספר מקורות מתועדים. קו מסירה רציף: קשר לימוד מבוסס במקור רבני. קו מסירה מקווקו: חסר ביסוס ישיר או שנותרה שאלת זיהוי / מקורות חלוקים. סימון הקשרים האחרים נקבע לפי סוגם. עיגול מקווקו: זהות או תקופה לבירור.</div>
 <div className="kg-work"><div className="kg-library"><label htmlFor="kg-search">חיפוש חכם</label><input id="kg-search" placeholder="שם החכם…" value={query} onChange={e=>setQuery(e.target.value)}/><label htmlFor="kg-scope">אוכלוסייה</label><select id="kg-scope" value={scope} onChange={e=>{setScope(e.target.value);clear();}}><option value="all">כל הפיילוט</option><option value="core">חכמי פרקי אבות</option><option value="one_hop">הרחבה בלבד</option><option value="review">דורשים בירור מעמיק</option></select><label htmlFor="kg-period">מעבר לתקופה</label><select id="kg-period" value="" onChange={e=>jump(e.target.value)}><option value="">בחרו דור…</option>{graph.bands.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select><label htmlFor="kg-family">סוג קשר</label><select id="kg-family" value={family} onChange={e=>{setFamily(e.target.value);setEdgeId(null);}}><option value="all">כל הקשרים</option>{Object.entries(names).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><label className="kg-check"><input type="checkbox" checked={certain} onChange={e=>{setCertain(e.target.checked);setEdgeId(null);}}/>רק קשרים מבוססים במקור</label>{query.trim()&&<div className="kg-list" aria-label="תוצאות חיפוש">{searchPeople.slice(0,15).map(p=><button className={selected===p.id?'active':''} key={p.id} onClick={()=>choose(p.id)}><span>{p.name}</span><small>{p.group==='core'?'ליבת אבות':'קשר ישיר לליבה'}</small></button>)}{!searchPeople.length&&<p>אין תוצאות בסינון הנוכחי.</p>}</div>}</div>
 <div className="kg-canvas">{!visible.length&&<p className="kg-no-branches">אין ענפים להצגה בסינון הזה. בחרו ״כל הפיילוט״ או סוג קשר אחר.</p>}<div className="kg-canvas-top"><span>{local&&person?`סביב ${person.name}`:'סדר הדורות · מוקדם למעלה, מאוחר למטה'}</span><label className="kg-check"><input type="checkbox" disabled={!selected} checked={local} onChange={e=>setLocal(e.target.checked)}/>רק קשרים ישירים של הנבחר</label></div><svg ref={svg} viewBox="-600 -430 1200 860" aria-label="מפת קשרים אינטראקטיבית; אפשר לבחור חכם גם ברשימה" onWheel={e=>{const box=svg.current!.getBoundingClientRect();const scale=box.width&&box.height?Math.min(box.width/1200,box.height/860):1;const unit=e.deltaMode===1?16:e.deltaMode===2?(box.height||600):1;setView(v=>({...v,x:v.x-e.deltaX*unit/scale,y:v.y-e.deltaY*unit/scale}));}} onPointerDown={e=>{if(e.button===1)e.preventDefault();if((e.target as Element).closest('[data-node],[data-edge]'))return;const box=svg.current!.getBoundingClientRect();drag.current={id:e.pointerId,p:{x:e.clientX,y:e.clientY},view,moved:false};if(box.width)svg.current!.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const scale=Math.min(svg.current!.clientWidth/1200,svg.current!.clientHeight/860);if(Math.hypot(e.clientX-d.p.x,e.clientY-d.p.y)>5)d.moved=true;setView({...d.view,x:d.view.x+(e.clientX-d.p.x)/scale,y:d.view.y+(e.clientY-d.p.y)/scale});}} onPointerUp={()=>{if(drag.current&&!drag.current.moved)clear();drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <defs>{Object.keys(names).map(f=><marker key={f} id={'arrow-'+f} markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,0 L7,3 L0,6" fill={colors[f]}/></marker>)}</defs><g transform={`translate(${view.x},${view.y}) scale(${view.z})`}>{graph.bands.map((band,i)=><g key={band.label} pointerEvents="none"><rect x={-graph.width/2} y={band.y} width={graph.width} height={(graph.bands[i+1]?.y??graph.height)-band.y} fill={i%2?"#e9ebe5":"#faf6e9"}/><text x={0} y={band.y+24} textAnchor="middle" fill="#a5a699" fontSize={16}>{band.label}</text></g>)}
 {edges.map(e=>{const active=e.a===selected||e.b===selected;return <g key={e.id} data-edge="true" data-source={e.a} data-target={e.b} onClick={()=>setEdgeId(e.id)} role="button" tabIndex={0} aria-label={`${names[e.family]}: ${data.people.find(p=>p.id===e.a)?.name} אל ${data.people.find(p=>p.id===e.b)?.name}`} onKeyDown={k=>{if(k.key==='Enter'||k.key===' '){k.preventDefault();setEdgeId(e.id);}}}><path d={straightPath(positions.get(e.a)!,positions.get(e.b)!,radius(e.a),radius(e.b))} fill="none" stroke="transparent" strokeWidth={16}/><path d={straightPath(positions.get(e.a)!,positions.get(e.b)!,radius(e.a),radius(e.b))} fill="none" pointerEvents="none" stroke={colors[e.family]} strokeWidth={edgeId===e.id?4:active?2.5:1.2} opacity={selected&&!active?.10:.62} strokeDasharray={e.state!=='known'?'6 5':e.family==='bar_plugta'?'2 5':e.family!=='teacher_student'?'10 5':undefined} markerEnd={e.directional?`url(#arrow-${e.family})`:undefined}/></g>;})}
 {visible.map(p=>{const pos=positions.get(p.id)!,highlight=neighbors.has(p.id),match=query&&p.name.includes(query);return <g key={p.id} data-node="true" data-person-id={p.id} transform={`translate(${pos.x},${pos.y})`} tabIndex={0} role="button" aria-label={p.name} onClick={()=>choose(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(p.id);}}} opacity={selected&&!highlight&&!match?.25:1}><title>{`${p.name} · ${knowledge.get(p.id)} מקורות מתועדים`}</title><circle strokeDasharray={p.review?"5 4":undefined} r={radius(p.id)} fill={selected===p.id?'#f0dfb4':p.group==='core'?'#fffcf3':'#ecebe3'} stroke={selected===p.id||match?'#b58c3e':'#b6c1ac'} strokeWidth={selected===p.id?4:2}/><text y={5} textAnchor="middle" fill="#59664f" fontSize={16} pointerEvents="none">{initials(p.name)}</text><text y={radius(p.id)+21} textAnchor="middle" fill="#354534" fontSize={selected===p.id?21:18} paintOrder="stroke" stroke="#faf7ed" strokeWidth="4">{p.name.length>23?p.name.slice(0,22)+"…":p.name}</text></g>;})}</g></svg>
 <div className="kg-zoom"><button aria-label="התקרבות" onClick={()=>zoom(1.25)}>＋</button><span>{Math.round(view.z*100)}%</span><button aria-label="התרחקות" onClick={()=>zoom(.8)}>−</button><button onClick={fit} aria-label="איפוס המפה">⌖</button></div><div className="kg-legend">{Object.entries(names).map(([f,n])=><span key={f}><i style={{background:colors[f]}}/>{n}</span>)}</div><span className="kg-help">גלילה למעבר בין דורות · זום בכפתורי ＋ / − · גרירה להזזה</span></div>
 {(person||edge)&&<aside className="kg-detail" aria-label="כרטיס חכם ומקורות" aria-live="polite"><button className="kg-close" onClick={clear} aria-label="סגירת החלונית">×</button>{edge?<><button onClick={()=>setEdgeId(null)}>סגירת הקשר ×</button><span className="kg-eyebrow">{names[edge.family]}</span><h2>{data.people.find(p=>p.id===edge.a)?.name}</h2><p>{edge.directional?'אל':'עם'} <button onClick={()=>choose(edge.b)}>{data.people.find(p=>p.id===edge.b)?.name}</button></p><span className="kg-status">{edge.state==='known'?'מבוסס במקור רבני':edge.state==='disputed'?'מחלוקת נוסח או זיהוי':'קשר מוצע לבדיקה'}</span><p>{edge.note}</p><h3>הראיות לקשר</h3>{sourceList(edge.citations)}</>:person?<><span className="kg-eyebrow">{person.group==='core'?'ליבת פרקי אבות':'הרחבה בקשר ישיר'}</span><h2>{person.name}</h2>{person.review&&<span className="kg-status">זהות או תקופה לבירור — פירוט להלן</span>}{person.note&&<p>{person.note}</p>}{person.summary&&<><h3>בקצרה</h3><p className="kg-summary">{person.summary.text}</p><details><summary>מקורות התקציר</summary>{sourceList(person.summary.citations)}</details></>}{person.review&&<p className="kg-muted">{person.reviewNote||"עיגול מקווקו: זהות או תקופה דורשות בירור נוסף."}{graph.anchors.has(person.id)?" המיקום ליד דמות קשורה הוא לצורכי תצוגה בלבד, ואינו קביעה של דור.":""}</p>}<h3>הערך והמקורות</h3>{person.facts.map((f,i)=><details key={i}><summary>{f.text}</summary>{sourceList(f.citations)}</details>)}{person.teachings.map((t,i)=><details key={i}><summary>אמירה מאבות</summary><blockquote>{t.text}</blockquote>{sourceList([t.citation])}</details>)}<h3>תקופה ודור</h3><p>{person.chronology.label}</p><p className="kg-muted">{person.chronology.note}</p>{sourceList(person.chronology.source_citation_ids)}<p className="kg-muted">השיוך לתקופה הוא הערכה מתועדת; אינו שנת לידה או פטירה.</p><PlacesOfActivity personId={person.id}/><h3>רבותיו</h3>{relationList(teachers,'לא תועדו רבותיו במאגר הנוכחי.')}<h3>תלמידיו</h3>{relationList(students,'לא תועדו תלמידיו במאגר הנוכחי.')}<h3>קשרים נוספים</h3>{relationList(otherRelations,'לא תועדו קשרים נוספים.')}<h3>מקורות להרחבה</h3><div className="kg-reading">{person.reading.map((r,i)=><a key={i} href={r.url} target="_blank" rel="noopener noreferrer">{r.label} ↗</a>)}{!person.reading.some(r=>(r.kind==='hebrewbooks'||r.kind==='heiman'))&&<p className="kg-muted">טרם אותר קישור מאומת לערך ב״תולדות תנאים ואמוראים״.</p>}</div></>:<div className="kg-empty"><span>✧</span><h2>כל חכם והקשרים שלו</h2><p>בחרו חכם במפה או ברשימה כדי לפתוח את כרטיסו. לחצו על קו כדי לקרוא את המקור לקשר.</p><button onClick={()=>choose(data.people.find(p=>p.name==='רבי עקיבא')!.id)}>התמקדות ברבי עקיבא ←</button><p className="kg-muted">המידע מוצג מתוך פיילוט אבות. עודכן {data.updated}. אין להסיק מהתרשים רשימה ממצה של כל הקשרים.</p></div>}</aside>}</div></section>;
}





