import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {read as parentRead,wikiPages,wikiText,hash} from '../lib.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url));
const read=f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'));
const write=(f,x)=>fs.writeFileSync(path.join(dir,f),typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const counts=read('counts.json'),changes=read('change-report.json'),audit=read('adjudication-audit.json'),validation=read('validation-report.json');
const pages=wikiPages('raw/wiki');
const snapshot=id=>{const p=pages.find(p=>p.pageid===id);return {pageid:id,title:p.title,revision:p.revisions[0].revid,url:'https://he.wikipedia.org/w/index.php?oldid='+p.revisions[0].revid,text:wikiText(p)};};
const entries=parentRead('hyman-entries.json');
const section=k=>{const e=entries.find(e=>e.key===k);return {key:k,title:e.title,volume:e.volume,pages:e.parts.map(p=>p.page),sources:e.parts.map(p=>p.url),text:e.text};};
write('priority-research-cases.json',[
  {case_id:'hamnuna-numbering',status:'unresolved_crosswalk',finding:'Numbering differs across references. Sefaria I combines features assigned by Hyman to II (pupil of Rav) and III (Rav Huna/Rav Hisda context). A disambiguation-page link is not a person identifier.',decision:'No crosswalk based on Roman/Arabic numbers. Retain profiles separately as review candidates until each passage and relationship is assigned.',sources:[snapshot(873860),snapshot(588208),snapshot(873859),section('hyman-section:6751210f903508fb6e3e'),section('hyman-section:c80e6abea8a365f2c402')],next_step:'Compare Eruvin 54a, Kiddushin 29b, Eruvin 63a and the traditional biography source by source. Preserve disagreement about which Hamnuna is intended.'},
  {case_id:'yehudah-ben-beteira',status:'unresolved_crosswalk',finding:'Wikipedia explicitly distinguishes first and second; Sefaria links both profiles to the first article. Both academy descriptions alone are insufficient to assign every citation.',decision:'Do not merge the numbered profiles or import the first article into both. The traditional proposal of two people is retained with its cited basis.',sources:[snapshot(492723),snapshot(1827917)],next_step:'Read Tosafot Menachot 65b and Hyman volume II printed pages 555–558; distinguish explicit identification from the tentative wording of Tosafot; validate Pesachim 3b separately from later teaching traditions.'},
  {case_id:'yitzhak-profile-and-passages',status:'profile_resolved_passages_quarantined',finding:'Tanna profile linked to the independently identified Tanna; 18 mixed topic assignments excluded from accepted primary evidence. Two independently cited Yerushalmi anchors retained.',decision:'Do not move all excluded passages to a single Amora; full names in several passages already point to different sages.',sources:[snapshot(960270),snapshot(699587)],next_step:'Assign quarantined passages to Yitzhak of Kefar Akko, Yitzhak bar Avdimi, Yitzhak bar Yehudah or other identities only after direct contextual comparison.'},
  {case_id:'aha-profile-and-passages',status:'profile_resolved_passages_quarantined',finding:'Lod, fourth generation and Yehudah ben Pazzi establish the Amora profile; the tag collection includes passages also assigned to the Tanna Aha.',decision:'Merged the profile with the matching Amora; quarantined all 20 existing topic-derived anchors rather than retaining mixed assignments.',sources:[snapshot(995178),snapshot(1351820)],next_step:'Reassign each passage individually; preserve the distinction between the Tanna, the Palestinian Amora and other Rav Aha identities.'}
]);
write('source-coverage-report.json',{...parentRead('source-coverage-report.json'),adjudication_round:{new_corpus_downloads:0,basis:'Reassessment of previously retained full-text and identity snapshots; original coverage unchanged.',explicit_hyman_classifications_recovered:audit.filter(x=>x.action==='recover_explicit_classification').length,primary_assignments_quarantined:counts.quarantined_primary_assignments,limitations:'No claim of new corpus coverage or exhaustive historical adjudication.'}});
write('source-coverage-report.md',fs.readFileSync(path.join(dir,'..','source-coverage-report.md'),'utf8')+'\n## Adjudication v2\n\nThis pass reuses the retained source snapshots; no additional corpus was downloaded. It recovers explicit Hyman classifications, inspects identity cases, distinguishes bibliographic/collective headings, and quarantines mixed passage assignments. Source URLs and revision IDs are retained in the audit and priority case files.\n');
const checks=validation.checks.map(c=>`- ${c.check}: ${c.status}`).join('\n');
write('validation-report.md',`# Validation — adjudication v2\n\n${validation.result}\n\n${checks}\n\nAll ${changes.input_conservation.input} original records are accounted for as retained person candidates, reference inventory or explicit redirects. Text and name occurrence were checked in the retained full corpus. This does not prove that every upstream identity annotation is correct. Chronology is only tested where dates are available. The validation deliberately does not certify completion of historical identity research.\n`);
write('methodology.md',`# Adjudication v2 methodology\n\nThe number of individually identifiable Tannaim and Amoraim found according to the Toladot methodology and processed source corpus.\n\nThe count is the currently accepted research subset, not a final census of all historical sages. Unresolved candidate records are excluded, and are not equivalent to additional people.\n\n1. Preserve the original dataset and all source snapshots. Rebuild this directory from those inputs.\n2. Separate bibliographic see-references, patronymic name indexes and collective headings from individual identities. A see-reference never means the two names are the same person.\n3. Merge only documented cases: consecutive fragments of a single biography, explicit alias equations, or manually compared names, primary teachings and biographical context. Honorific normalization only discovers candidates.\n4. Recover historical classification only from explicit headings/subtitles. Do not classify a reciter of baraitot as a historical Tanna merely because he is called a tanna. Preserve variant-text cautions.\n5. Separate profile identity from passage attribution. Quarantine contaminated annotation sets; do not transfer them wholesale to another homonym.\n6. Retain independent generation schemes and source assertions. Do not invent dates, identifiers or teacher relationships. Relationships from merged records are retained as untransferred source fields pending assertion-level review.\n7. Reopen formerly accepted identities when a new possible duplicate appears. Count accuracy takes priority over increasing the total.\n8. Keep a source-backed decision audit, old-to-new ID redirects, excluded evidence and a prioritized queue for every surviving unresolved candidate.\n\nRun from this directory: node adjudicate.mjs; node validate.mjs; node reports.mjs. All outputs remain research-only. The baseline, application and live database are unchanged.\n`);
write('README.md',`# בירור זהויות — סבב 2\n\nהסבב נשמר בנפרד מהמאגר הקודם ומהאתר. הבירור ההיסטורי הכולל עדיין לא הושלם.\n\n- **${counts.total_unique_sages} זהויות בספירה השמרנית הנוכחית**: ${counts.tannaim} תנאים ו־${counts.amoraim} אמוראים.\n- ${changes.promoted_from_review.length} רשומות עברו מתור הבירור למאגר המזוהה.\n- ${counts.merged_source_records} רשומות אוחדו לרשומות קיימות עם ראיות מתועדות.\n- ${counts.bibliographic_inventory_records} הפניות, מפתחות וקבוצות הופרדו מרשומות אנשים.\n- ${counts.quarantined_primary_assignments} שיוכי מקורות הוצאו מן הראיות המאושרות לבירור נפרד.\n- ${changes.demoted_from_master.length} רשומות שהיו מאושרות חזרו לבירור עקב חשד חדש לכפילות.\n- נותרו **${counts.manual_review_candidate_records} רשומות מועמדות** לבירור; אין פירוש הדבר שיש עוד מספר כזה של חכמים.\n\nהמספר ירד מ־790 בעקבות תיקון כפילויות והחזרה זהירה של מקרים לבדיקה. אין לראות בו מספר סופי של כל התנאים והאמוראים.\n\n| מדד | מספר |\n|---|---:|\n| תנאים | ${counts.tannaim} |\n| אמוראים | ${counts.amoraim} |\n| אמוראים — ארץ ישראל | ${counts.amoraim_eretz_israel} |\n| אמוראים — בבל | ${counts.amoraim_babylonia} |\n| אמוראים — מעורב או לא ידוע | ${counts.amoraim_mixed_unknown} |\n| סך הכול מזוהים | ${counts.total_unique_sages} |\n| ביטחון גבוה | ${counts.high_confidence_identities} |\n| ביטחון בינוני | ${counts.medium_confidence_identities} |\n| רשומות בתור הבירור | ${counts.manual_review_candidate_records} |\n| זוגות חשודים בכפילות | ${counts.suspected_duplicate_pairs} |\n| רשומות עם ראיה ראשונית ישירה | ${counts.records_with_direct_primary_chazal_evidence} |\n\n## דוגמאות להכרעות\n\n- רבי חנינא בר חמא: פיצול של אותו ערך, עם משפט שנמשך בין שני עמודים.\n- שמעון בן ננס / בן ננס: זיהוי מפורש במקורות; הוסרה ספירה כפולה.\n- רבי חייא בר נחמני ותוטאי: השוואת הדיבור המפורש בברכות מח ע״ב ובקידושין טז ע״ב לערך הביוגרפי.\n- רבי יצחק ורבי אחא: הפרדה בין זיהוי האדם לבין תיוגים שגויים של קטעי תלמוד.\n- רב המנונא ורבי יהודה בן בתירא: תועדו שאלות הזהות שנותרו פתוחות; לא אוחדו לפי מספור בלבד.\n\n## קבצים\n\n- [מאגר מזוהה](master-sages.json)\n- [תור בירור מדורג עם מקורות](review-queue.json)\n- [רשומות בירור מלאות](manual-review-identities.json)\n- [יומן הכרעות וראיות](adjudication-audit.json)\n- [תיקי מחקר מורכבים](priority-research-cases.json)\n- [שיוכי מקורות שנפסלו לעת עתה](quarantined-primary-assignments.json)\n- [הפניות וקבוצות שאינן נספרות כאדם](bibliographic-inventory.json)\n- [דוח שינויים](change-report.json)\n- [בדיקות](validation-report.md)\n- [כיסוי מקורות](source-coverage-report.md)\n- [שיטת העבודה](methodology.md)\n\nהבדיקות המבניות עברו. הן אינן תחליף לבדיקה היסטורית של כל שיוך או לכללי כרונולוגיה כשחסרים תאריכים.\n`);
write('baseline-input-hashes.json',Object.fromEntries(['master-sages.json','manual-review-identities.json','hyman-entries.json','suspected-duplicates.json'].map(f=>[f,hash(fs.readFileSync(path.join(dir,'..',f),'utf8'))])));
console.log('Reports written; '+counts.total_unique_sages+' accepted identities; '+counts.manual_review_candidate_records+' unresolved candidate records.');
