import fs from 'node:fs';import path from 'node:path';import {root,read as parentRead,norm,flatRef} from '../lib.mjs';
const local=path.join(root,'adjudication-v3');
const read=n=>['corpus-manifest.json','merge-audit.json'].includes(n)||n.startsWith('raw/')?parentRead(n):JSON.parse(fs.readFileSync(fs.existsSync(path.join(local,n))?path.join(local,n):path.join(root,'adjudication-v2',n),'utf8'));
const write=(n,d)=>fs.writeFileSync(path.join(local,n),JSON.stringify(d,null,2)+'\n');
const master=read('master-sages.json'),review=read('manual-review-identities.json').records,all=[...master.sages,...review],manifest=read('corpus-manifest.json');const findings=[],checks=[];
const group=(items,key)=>{const m=new Map();for(const r of items){const k=key(r);if(k===null||k===undefined)continue;const a=m.get(k)||[];a.push(r);m.set(k,a);}return [...m].filter(([,a])=>a.length>1).map(([key,a])=>({key,identities:a.map(r=>r.identity_key)}));};
const duplicateIds=group(all,r=>r.person_id);checks.push({check:'duplicate_person_ids',status:duplicateIds.length?'fail':'pass',findings:duplicateIds});
const duplicateKeys=group(all,r=>r.identity_key);checks.push({check:'duplicate_identity_keys',status:duplicateKeys.length?'fail':'pass',findings:duplicateKeys});
const duplicateCanonical=group(master.sages,r=>norm(r.canonical_name_he));checks.push({check:'duplicate_canonical_people_in_counted_dataset',status:duplicateCanonical.length?'fail':'pass',findings:duplicateCanonical,note:'Canonical-name and external-ID checks cannot prove the absence of all unknown aliases.'});
for(const field of ['wikidata','hewiki_pageid','bonayich']){const duplicates=group(master.sages,r=>r.external_ids[field]);checks.push({check:'duplicate_external_person_id_'+field,status:duplicates.length?'fail':'pass',findings:duplicates});}
const classConflicts=master.sages.filter(r=>new Set(r.classification_assertions.map(x=>x.value)).size>1);checks.push({check:'tanna_amora_conflicts_in_counted_dataset',status:classConflicts.length?'fail':'pass',findings:classConflicts.map(r=>r.identity_key),quarantined:review.filter(r=>new Set(r.classification_assertions.map(x=>x.value)).size>1).length});
const generationConflicts=all.filter(r=>r.generation.some((g,i)=>r.generation.some((h,j)=>i!==j&&g.scheme===h.scheme&&g.scheme==='Sefaria person-collection'&&g.value!==h.value)));checks.push({check:'generation_conflicts',status:generationConflicts.length?'review':'pass',findings:generationConflicts.map(r=>({identity:r.identity_key,generations:r.generation})),note:'Sefaria and Wikipedia generation numbering are separate schemes. Multiple adjacent-generation Wikipedia categories are not automatically contradictions.'});
const impossible=all.filter(r=>r.birth_year!==null&&r.death_year!==null&&r.birth_year>r.death_year);const dated=all.filter(r=>r.birth_year!==null&&r.death_year!==null);const ids=new Map(all.map(r=>[r.person_id,r]));let chronologyTested=0;const relationshipConflicts=[];
for(const r of all)for(const t of r.teachers||[]){const teacher=ids.get(t.target_person_id);if(r.birth_year!==null&&teacher?.death_year!==null&&teacher?.death_year!==undefined){chronologyTested++;if(r.birth_year>teacher.death_year)relationshipConflicts.push({student:r.identity_key,teacher:teacher.identity_key,birth:r.birth_year,teacher_death:teacher.death_year,source:t.source});}}
checks.push({check:'impossible_chronology',status:impossible.length||relationshipConflicts.length?'review':'pass_with_missing_data',birth_death_pairs_tested:dated.length,teacher_student_pairs_tested:chronologyTested,findings:[...impossible.map(r=>({identity:r.identity_key,birth:r.birth_year,death:r.death_year})),...relationshipConflicts],note:'Unknown dates remain null; untestable chronology is not certified as valid.'});
const corpusCache=new Map();let verified=0;for(const r of master.sages)for(const e of r.primary_chazal_evidence){const b=manifest.books.find(b=>b.title===e.book);if(!b){findings.push({identity:r.identity_key,ref:e.ref,error:'book_not_in_manifest'});continue;}let d=corpusCache.get(b.key);if(!d){d=read('raw/corpus/'+b.key+'.json');corpusCache.set(b.key,d);}const text=d.text[e.export_segment_key];if(typeof text!=='string'||!text.trim()){findings.push({identity:r.identity_key,ref:e.ref,error:'empty_or_missing_source_segment'});continue;}if(flatRef(d,e.export_segment_key)!==e.ref)findings.push({identity:r.identity_key,ref:e.ref,error:'reference_coordinate_mismatch'});if(e.mention&&!norm(text).includes(norm(e.mention)))findings.push({identity:r.identity_key,ref:e.ref,error:'attributed_name_not_in_source_segment',mention:e.mention});else verified++;}
checks.push({check:'primary_source_segment_and_name_verification',status:findings.length?'fail':'pass',verified_evidence_records:verified,findings,note:'Checked against downloaded full text and retained export coordinates. This proves textual occurrence, not infallibility of upstream identity attribution.'});
const noSources=master.sages.filter(r=>!r.primary_chazal_evidence.length||!r.secondary_identity_evidence.length);checks.push({check:'counted_records_without_primary_or_identity_sources',status:noSources.length?'fail':'pass',findings:noSources.map(r=>r.identity_key)});
const merges=[...read('merge-audit.json'),...read('adjudication-audit.json').filter(x=>x.action==='same_person')];checks.push({check:'suspicious_merges',status:'reviewable_audit',merges:merges.length,merges_without_basis:merges.filter(x=>!x.basis&&!x.reason).length,note:'All merges retain a basis. Exact-name/common-passage merges remain medium confidence; no generic see-entry cross-reference is an identity merge.'});
const change=read('change-report.json');checks.push({check:'input_record_conservation',status:change.input_conservation.input===change.input_conservation.output?'pass':'fail',...change.input_conservation});
const quarantined=read('quarantined-primary-assignments.json');const ta=master.sages.find(r=>r.identity_key==='hewiki:960270');checks.push({check:'mixed_yitzhak_topic_assignments_quarantined',status:quarantined.filter(q=>q.original_identity_key==='sefaria:rabbi-yitzhak').length===18&&ta&&!ta.primary_chazal_evidence.some(e=>quarantined.some(q=>q.evidence.ref===e.ref))?'pass':'fail'});
checks.push({check:'collectives_not_counted_as_people',status:master.sages.some(r=>/^(בית |בני |רבנן|חכמי|זקני|זקנים הראשונים|אנשי ירושלים)/.test(r.canonical_name_he||''))?'fail':'pass'});
const counts=master.counts;checks.push({check:'count_reconciliation',status:counts.tannaim+counts.amoraim===counts.total_unique_sages&&counts.amoraim_eretz_israel+counts.amoraim_babylonia+counts.amoraim_mixed_unknown===counts.amoraim&&counts.high_confidence_identities+counts.medium_confidence_identities===counts.total_unique_sages?'pass':'fail'});
write('validation-report.json',{generated_at:new Date().toISOString(),result:checks.some(x=>x.status==='fail')?'FAILED':'PASSED_STRUCTURAL_CHECKS_WITH_RESEARCH_LIMITATIONS',checks,manual_review_candidate_records:review.length,not_certified:['Exhaustive identification of every historical person','Complete chronology for undated people','Complete teacher/student/family graph','Automatic NER and encyclopedia identity decisions as infallible']});
console.log(checks.map(x=>x.check+': '+x.status).join('\n'));if(checks.some(x=>x.status==='fail'))process.exitCode=1;
