import {read,write,wikiPages,wikiText,norm,clean,hash} from './lib.mjs';
const groups=new Map(),unsegmented=[];
const pages=wikiPages('raw/heiman-text').sort((a,b)=>a.title.localeCompare(b.title,'en',{numeric:true}));
for(const p of pages){const text=wikiText(p),volume=p.title.match(/veAmoraim\. (I+)\./)?.[1],page=Number(p.title.split('/').at(-1));if(!volume)continue;const tags=[...text.matchAll(/<קטע (התחלה|סוף)=([^>]+)\/>|<section\s+(begin|end)\s*=\s*["']([^"']+)["']\s*\/>/g)];let starts=0;
 for(let i=0;i<tags.length;i++){const m=tags[i],kind=m[1]||m[3],title=(m[2]||m[4]).trim();if(kind!=='התחלה'&&kind!=='begin')continue;starts++;const end=tags.slice(i+1).find(x=>(x[2]||x[4]).trim()===title&&['סוף','end'].includes(x[1]||x[3]));const body=text.slice(m.index+m[0].length,end?.index??text.length).replace(/<noinclude>[\s\S]*?<\/noinclude>/g,'');const key=volume+':'+title;const g=groups.get(key)||{key:'hyman-section:'+hash(key).slice(0,20),volume,title,parts:[]};g.parts.push({page,title:p.title,pageid:p.pageid,revision:p.revisions[0].revid,quality:text.match(/pagequality level="(\d)"/)?.[1]||null,body,url:'https://he.wikisource.org/w/index.php?oldid='+p.revisions[0].revid});groups.set(key,g);}
 if(!starts)unsegmented.push({page:p.title,pageid:p.pageid,revision:p.revisions[0].revid,characters:text.length});
}
const entries=[];for(const e of groups.values()){e.text=e.parts.map(x=>x.body).join('\n');const body=clean(e.text.replace(/^=+[^\n]+?=+\s*/gm,'').replace(/\[\[(?:[^|\]]+\|)?([^\]]+)\]\]/g,'$1'));e.classification=null;e.classification_basis=null;const lead=body.slice(0,250);
 const tm=lead.match(/^(?:היה\s+)?(?:מגדולי\s+)?תנא(?:[\s,.]|$)|^.{0,65}?היה\s+(?:אחד\s+מ|מגדולי\s+)?תנא(?:[\s,.]|$)/);const am=lead.match(/^(?:היה\s+)?(?:מגדולי\s+)?אמורא(?:[\s,.]|$)|^.{0,65}?היה\s+(?:אחד\s+מ|מגדולי\s+)?אמורא(?:[\s,.]|$)/);
 if(tm&&!am){e.classification='Tanna';e.classification_basis=tm[0];}if(am&&!tm){e.classification='Amora';e.classification_basis=am[0];}
 e.redirect_target=body.match(/^(?:עיין\s+)?ערך\s+(.{2,100}?)[.]?$/)?.[1]?.replace(/[.]$/,'')||null;
 e.identity_caution=/ט"ס|טעות סופר|צ"ל|ספק|מסופק|לא מצאתי|לא נמצא|גרסא|גרסת|אין זה|אינו אלא/.test(body.slice(0,800));e.nonperson=/כל החכמים|\(תואר\)|\(סתם\)|סימני הש"ס|^הקדמה$/.test(e.title);
 e.reference_links=[...e.text.matchAll(/\[\[([^|\]]+)(?:\|[^\]]*)?\]\]/g)].map(x=>x[1]);e.distinct_nonadjacent_parts=e.parts.some((p,i)=>i>0&&p.page>e.parts[i-1].page+1);entries.push(e);
}write('hyman-entries.json',entries);write('hyman-text-coverage.json',{transcribed_pages:pages.length,sections:entries.length,unsegmented_pages:unsegmented,quality_counts:pages.reduce((a,p)=>{const k=wikiText(p).match(/pagequality level="(\d)"/)?.[1]||'unknown';a[k]=(a[k]||0)+1;return a;},{})});console.log('Hyman sections',entries.length,'explicit classification',entries.filter(x=>x.classification).length,'cross-reference-only',entries.filter(x=>x.redirect_target).length,'unsegmented',unsegmented.length);
