import fs from 'node:fs';import path from 'node:path';import {root,read,write,uuid,norm,clean,csv,wikiPages,wikiText} from './lib.mjs';
const records=new Map(),keyMap=new Map(),merges=[],excluded=[],heimanTargets=new Map();
function add(key,name,en,aliases,source,classification=null){const r={person_id:uuid(key),identity_key:key,canonical_name_he:name||null,canonical_name_en:en||null,aliases:aliases||[],classification,classification_assertions:classification?[{value:classification,source}]:[],generation:[],region:'unknown',region_assertions:[],teachers:[],students:[],family:[],locations:[],primary_chazal_evidence:[],secondary_identity_evidence:[source],notes:[],review_reasons:[],external_ids:{},traditional_identification:null,scholarly_disagreements:[],birth_year:null,death_year:null};records.set(key,r);keyMap.set(key,key);return r;}
function source(kind,url,detail,extra={}){return {kind,url,detail,...extra};}
const topics=read('raw/topics.json');const selected=read('topic-manifest.json').filter(x=>x.status==='downloaded');
for(const {slug} of selected){const t=read('raw/topic-details/'+encodeURIComponent(slug)+'.json');if(!t.titles){excluded.push({key:'sefaria:'+slug,reason:'Dangling topic-graph target: API returned no identity metadata.'});continue;}const g=t.properties?.generation?.value;const cls=/^T\d/.test(g)?'Tanna':/^A\d/.test(g)?'Amora':null;const s=source('sefaria_identity','https://www.sefaria.org/topics/'+slug,'Sefaria person record; source metadata retained',{properties:t.properties||{}});const r=add('sefaria:'+slug,t.he,t.en,t.titles.map(x=>({name:x.text,language:x.lang,source:s.url})),s,cls);r.external_ids.sefaria_slug=slug;if(g)r.generation.push({scheme:'Sefaria person-collection',value:g,source:s.url});r.identity_description=t.description||{};if(t.properties?.dedup_needed?.value==='true')r.notes.push('Sefaria upstream marks dedup_needed; independently check aliases and external identifiers.');if(g==='TA')r.notes.push('Sefaria marks a Tanna–Amora transition, not two people. Classification requires secondary evidence.');for(const k of ['heWikiLink','enWikiLink','jeLink'])if(t.properties?.[k]?.value)r.secondary_identity_evidence.push(source(k==='jeLink'?'jewish_encyclopedia_link':'encyclopedia_link',t.properties[k].value,'Link supplied by Sefaria; retrieval status evaluated separately.'));}
const reconciliation=csv(fs.readFileSync(path.join(root,'raw/reconciliation.csv'),'utf8'));
const recon=new Map(reconciliation.filter(x=>x.bonayich&&x.Slug).map(x=>['BONAYICH:'+x.bonayich,x]));
for(const e of read('raw/sperling_named_entities.json')){if(e.tag!=='PERSON'){excluded.push({key:e.id,reason:'not_individual_person',tag:e.tag});continue;}const key='bonayich:'+e.id.split(':')[1],row=recon.get(e.id),target=row&&records.get('sefaria:'+row.Slug);const s=source('sefaria_bonayich','https://github.com/Sefaria/Sefaria-Data/blob/master/research/knowledge_graph/named_entity_recognition/external_named_entities/sperling_named_entities.json',e.id,{original_type:e.type});const cls=e.type==='תנא'?'Tanna':e.type==='אמורא'?'Amora':null;const aliases=e.manualTitles.map(x=>({name:x.text,language:x.lang,source:s.url}));if(target){target.aliases.push(...aliases);target.secondary_identity_evidence.push(s);target.external_ids.bonayich=e.id;keyMap.set(key,target.identity_key);if(cls)target.classification_assertions.push({value:cls,source:s});merges.push({from:key,to:target.identity_key,basis:'Explicit Sefaria Bonayich reconciliation CSV',row});}else{const r=add(key,aliases.find(x=>x.language==='he')?.name,aliases.find(x=>x.language==='en')?.name,aliases,s,cls);r.external_ids.bonayich=e.id;if(!cls)r.review_reasons.push('Reference identifies a person/contemporary but does not establish Tanna or Amora status.');}}
// Authoritative outgoing Hebrew-Wikipedia links identify pages; spelling similarity alone does not merge people.
const wiki=wikiPages('raw/wiki'),byTitle=new Map(wiki.map(x=>[x.title,x]));for(const f of fs.readdirSync(path.join(root,'raw/wiki'))){const d=read('raw/wiki/'+f);for(const x of d.query?.redirects||[])if(byTitle.has(x.to))byTitle.set(x.from,byTitle.get(x.to));for(const x of d.query?.normalized||[])if(byTitle.has(x.to))byTitle.set(x.from,byTitle.get(x.to));}
const wikiTargets=new Map();for(const r of records.values()){for(const s of r.secondary_identity_evidence){if(!/he\.wikipedia\.org\/wiki\//.test(s.url))continue;const title=decodeURIComponent(s.url.split('/wiki/')[1]).replaceAll('_',' '),p=byTitle.get(title);if(p){const targets=wikiTargets.get(p.pageid)||[];targets.push(r);wikiTargets.set(p.pageid,targets);}}}
for(const d of read('identity-decisions.json').rejected_external_links||[]){const list=wikiTargets.get(d.hewiki_pageid)||[];wikiTargets.set(d.hewiki_pageid,list.filter(r=>r.external_ids.sefaria_slug!==d.sefaria_slug));const r=records.get('sefaria:'+d.sefaria_slug);if(r)r.notes.push('Rejected upstream identity link: '+d.reason);}
for(const decision of read('identity-decisions.json').crosswalks){const r=records.get('sefaria:'+decision.sefaria_slug);if(r){const targets=wikiTargets.get(decision.hewiki_pageid)||[];if(!targets.includes(r))targets.push(r);wikiTargets.set(decision.hewiki_pageid,targets);r.notes.push(decision.basis);}}
for(const p of wiki){const text=wikiText(p),cats=(p.categories||[]).map(x=>x.title);const lead=clean(text.replace(/\{\{[\s\S]*?\}\}/g,' ').replace(/\[\[(?:[^|\]]+\|)?([^\]]+)\]\]/g,'$1').split(/\n==/)[0]).slice(0,1800);const t=cats.some(x=>/^קטגוריה:(הדור.+לתנאים|תנאים$|תנאי בבל$|הזוגות$)/.test(x));const a=cats.some(x=>/^קטגוריה:(?:הדור.+ל)?אמורא|^קטגוריה:נחותי$/.test(x));let cls=t&&!a?'Tanna':a&&!t?'Amora':null;
 if(!cls&&/^(?:[^.]{0,220})(?:היה|הוא|הייתה|היתה)\s+(?:מגדולי\s+|אחד\s+מ)?(?:ה)?תנא(?:י|ית)?(?:[\s,.;]|$)/.test(lead))cls='Tanna';
 if(!cls&&/^(?:[^.]{0,220})(?:היה|הוא)\s+(?:מגדולי\s+|אחד\s+מ)?(?:ה)?אמורא(?:[\s,.;]|$)/.test(lead))cls='Amora';
 const targets=wikiTargets.get(p.pageid)||[];if(!cls&&!targets.length&&!('disambiguation' in (p.pageprops||{}))){excluded.push({key:'hewiki:'+p.pageid,title:p.title,reason:'No sage classification; category traversal may include concepts, relatives, or other periods.'});continue;}
 const s=source('hebrew_wikipedia','https://he.wikipedia.org/w/index.php?oldid='+p.revisions[0].revid,p.title,{pageid:p.pageid,revision:p.revisions[0].revid,categories:cats});let r;
 if(targets.length===1){r=targets[0];keyMap.set('hewiki:'+p.pageid,r.identity_key);merges.push({from:'hewiki:'+p.pageid,to:r.identity_key,basis:'Explicit Sefaria outgoing Wikipedia identity link',source:s.url});r.secondary_identity_evidence.push(s);}else{r=add('hewiki:'+p.pageid,p.title,null,[{name:p.title,language:'he',source:s.url}],s,cls);if(targets.length>1){r.review_reasons.push('Several Sefaria identities link to this same Wikipedia page; disambiguation required.');for(const q of targets)q.review_reasons.push('Shared Wikipedia identity page '+p.pageid);}}
 r.external_ids.hewiki_pageid=p.pageid;r.external_ids.wikidata=p.pageprops?.wikibase_item||null;if(cls&&!r.classification)r.classification=cls;if(cls)r.classification_assertions.push({value:cls,source:s});
 if(t&&a)r.review_reasons.push('Wikipedia categories span both Tannaim and Amoraim; resolve transition/classification.');if('disambiguation' in (p.pageprops||{}))r.review_reasons.push('Wikipedia disambiguation page, not a single resolved person.');
 const ei=cats.some(x=>/אמוראי ארץ ישראל/.test(x)),ba=cats.some(x=>/אמוראי בבל/.test(x));r.region=ei&&ba?'mixed':ei?'Eretz Israel':ba?'Babylonia':r.region;if(ei||ba)r.region_assertions.push({value:r.region,source:s});
 for(const c of cats.filter(x=>/הדור|דור המעבר/.test(x)))r.generation.push({scheme:'Hebrew Wikipedia categories',value:c.replace('קטגוריה:',''),source:s.url});
 r.secondary_reference_links=[...text.matchAll(/https?:\/\/[^\s<>{}\]|]+/g)].map(x=>x[0]);r.wikipedia_wikitext_file='raw/wiki';
 for(const m of text.matchAll(/\{\{תולדות תנאים ואמוראים\|([^|}]+)\|([^|}]+)(?:\|[^}]*)?\}\}/g)){const title='תולדות תנאים ואמוראים/'+m[1].trim()+'/'+m[2].trim();const targets=heimanTargets.get(title)||[];targets.push(r.identity_key);heimanTargets.set(title,[...new Set(targets)]);}
 // Infobox values are preserved as source claims, not silently resolved as person IDs.
 for(const [field,labels] of [['teachers',['רבותיו']],['students',['תלמידיו']],['family',['אב','אם','בן זוג','בת זוג','ילדים']],['locations',['מקום פעילות','מקום מגורים']]])for(const label of labels){const m=text.match(new RegExp('\\|\\s*'+label+'\\s*=([^\\n]*)'));if(m?.[1]?.trim())r[field].push({raw_value:m[1].trim(),source:s.url,knowledge_state:'known',resolution:'unresolved_identifiers'});}
}
const wdDir=path.join(root,'raw/wikidata');if(fs.existsSync(wdDir))for(const f of fs.readdirSync(wdDir)){for(const e of Object.values(read('raw/wikidata/'+f).entities||{})){for(const r of records.values()){if(r.external_ids.wikidata!==e.id)continue;const s=source('wikidata','https://www.wikidata.org/wiki/'+e.id,'Structured identity claims; retained separately from primary evidence',{revision:e.lastrevid});r.secondary_identity_evidence.push(s);r.wikidata_claims=e.claims||{};for(const lang of ['he','en']){if(lang==='en'&&!r.canonical_name_en)r.canonical_name_en=e.labels?.en?.value||null;for(const x of e.aliases?.[lang]||[])r.aliases.push({name:x.value,language:lang,source:s.url});}}}}
// The reference entries remain distinct unless there is an explicit cross-reference.
for(const p of wikiPages('raw/heiman')){if(p.title.split('/').length<3)continue;const title=p.title.split('/').slice(2).join('/'),text=wikiText(p);if(/כל החכמים|\(תואר\)|\(סתם\)|^תוספות|^הערות/.test(title)){excluded.push({key:'heiman:'+p.pageid,title,reason:'Collective, title, or generic-name entry; not one person.'});continue;}
 const s=source('hyman_1910','https://he.wikisource.org/w/index.php?oldid='+p.revisions[0].revid,p.title,{pageid:p.pageid,revision:p.revisions[0].revid});const aliases=[{name:title,language:'he',source:s.url}];const targets=heimanTargets.get(p.title)||[];let r;if(targets.length===1){r=records.get(targets[0]);r.secondary_identity_evidence.push(s);r.aliases.push(...aliases);keyMap.set('heiman:'+p.pageid,r.identity_key);merges.push({from:'heiman:'+p.pageid,to:r.identity_key,basis:'Explicit Wikipedia template linking the exact Hyman identity entry',source:s.url});}else{r=add('heiman:'+p.pageid,title,null,aliases,s,null);r.review_reasons.push('Traditional reference entry: classification and identity reconciliation pending source-text assessment.');if(targets.length>1)r.review_reasons.push('Multiple Wikipedia persons refer to the same Hyman entry.');}r.external_ids.heiman_pageid=p.pageid;r.reference_transclusion=text.match(/<pages[\s\S]*?\/>/)?.[0]||null;r.reference_entry_wikitext=text;}
// Name list is a discovery inventory, never a census of people.
const names=csv(fs.readFileSync(path.join(root,'raw/RabbisNames.csv'),'utf8')).filter(x=>x.ID&&/^\d+$/.test(x.ID)).map(x=>({id:x.ID,name:Array.from({length:10},(_,i)=>x['Name'+(i+1)]).filter(Boolean).join(' '),linked_ids:x.LinkedID||null,notes:x.notes||null}));write('name-discovery-inventory.json',names);
for(const r of records.values()){
 if(r.external_ids.sefaria_slug){const d=read('raw/topic-details/'+encodeURIComponent(r.external_ids.sefaria_slug)+'.json');for(const [kind,field] of [['learned-from','teachers'],['taught','students']])for(const x of d.links?.[kind]?.links||[])r[field].push({target_identity_key:'sefaria:'+x.topic,source:'https://www.sefaria.org/topics/'+d.slug,source_data:x.dataSource,knowledge_state:'known',evidence_level:'secondary_identity_graph'});}
 for(const [prop,field] of [['P569','birth_year'],['P570','death_year']]){const values=(r.wikidata_claims?.[prop]||[]).filter(x=>x.rank!=='deprecated'&&x.mainsnak?.datavalue?.value?.precision>=9).map(x=>x.mainsnak.datavalue.value.time.match(/^([+-]\d+)-/)?.[1]).filter(Boolean).map(Number);if(new Set(values).size===1){r[field]=values[0];r[field+'_assertion']={source:'https://www.wikidata.org/wiki/'+r.external_ids.wikidata,knowledge_state:'estimated',note:'Year-level Wikidata assertion; raw claims, qualifiers and references retained.'};}}
 r.aliases=[...new Map(r.aliases.filter(x=>x.name).map(x=>[x.language+':'+x.name,x])).values()];const cls=[...new Set(r.classification_assertions.map(x=>x.value))];if(cls.length>1)r.review_reasons.push('Conflicting Tanna/Amora identity assertions.');}
write('candidate-identities.json',[...records.values()]);write('identity-key-map.json',Object.fromEntries(keyMap));write('merge-audit.json',merges);write('excluded-candidates.json',excluded);console.log('identity candidates',records.size,'explicit reconciliations',merges.length,'name inventory',names.length);
