import fs from 'node:fs';import path from 'node:path';import {root,read,write,norm} from './lib.mjs';
let records=read('scanned-identities.json');const audit=read('merge-audit.json'),removed=new Map(),duplicates=[];
const anchored=e=>/Sefaria|citation plus/.test(e.identity_attribution)&&e.evidence_stratum==='primary_corpus';
const cname=r=>norm(r.canonical_name_he||'');
const explicitNumber=r=>/\((?:[1-9]|[IVX]+|הראשון|השני|השלישי|הרביעי|החמישי|תנא|אמורא)\)/i.test(r.canonical_name_he||'');
const numbered=r=>/\((?:[1-9]|[IVX]+|הראשון|השני|השלישי|הרביעי|החמישי)\)/i.test((r.canonical_name_he||'')+' '+(r.external_ids.sefaria_slug||''));
const priority=r=>r.identity_key.startsWith('sefaria:')?0:r.identity_key.startsWith('hewiki:')?1:r.identity_key.startsWith('bonayich:')?2:3;
const compatible=(a,b)=>!(a.classification&&b.classification&&a.classification!==b.classification)&&!a.generation.some(g=>b.generation.some(h=>g.scheme===h.scheme&&g.scheme==='Sefaria person-collection'&&g.value!==h.value))&&!(a.birth_year&&b.death_year&&a.birth_year>b.death_year)&&!(b.birth_year&&a.death_year&&b.birth_year>a.death_year);
function merge(a,b,basis,proof){if(priority(b)<priority(a))[a,b]=[b,a];for(const field of ['aliases','generation','teachers','students','family','locations','primary_chazal_evidence','secondary_identity_evidence','classification_assertions','region_assertions','notes','review_reasons'])a[field]=[...(a[field]||[]),...(b[field]||[])];a.primary_chazal_evidence=[...new Map(a.primary_chazal_evidence.map(x=>[x.ref+'|'+x.identity_attribution,x])).values()];if(!a.classification)a.classification=b.classification;if(!a.canonical_name_en)a.canonical_name_en=b.canonical_name_en;if(a.region==='unknown')a.region=b.region;else if(b.region!=='unknown'&&a.region!==b.region)a.region='mixed';a.external_ids={...b.external_ids,...a.external_ids};if(!a.hyman_entry_text)a.hyman_entry_text=b.hyman_entry_text;if(!a.traditional_identification)a.traditional_identification=b.traditional_identification;removed.set(b.identity_key,a.identity_key);audit.push({from:b.identity_key,to:a.identity_key,basis,proof});return a;}
// Independent source anchors, not name-only equivalence, are required for automatic cross-source merges.
const aliasOwners=new Map();for(const r of records)for(const a of r.aliases.filter(a=>a.language==='he')){const n=norm(a.name),set=aliasOwners.get(n)||new Set();set.add(cname(r));aliasOwners.set(n,set);}
const groups=new Map();for(const r of records){const k=cname(r);const a=groups.get(k)||[];a.push(r);groups.set(k,a);}
for(const [name,list] of groups){if(list.length<2)continue;for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];if(removed.has(a.identity_key)||removed.has(b.identity_key))continue;const shared=a.primary_chazal_evidence.filter(anchored).find(e=>b.primary_chazal_evidence.some(f=>anchored(f)&&e.ref===f.ref));const sufficientlySpecific=name.split(' ').filter(x=>!['רבי','רב','רבן','בן','בר'].includes(x)).length>=2;
 if((sufficientlySpecific||(name.split(' ').length>=2&&aliasOwners.get(name)?.size===1))&&!explicitNumber(a)&&!explicitNumber(b)&&compatible(a,b)&&shared){merge(a,b,'Exact canonical name without a competing homonym, independently attributed common primary passage, compatible chronology/classification; no invented name numbering',{canonical_name:name,common_primary_ref:shared.ref,secondary_sources:[...a.secondary_identity_evidence,...b.secondary_identity_evidence].map(s=>s.url)});}
 else duplicates.push({identity_keys:[a.identity_key,b.identity_key],name,basis:'Same normalized canonical name; identity equivalence not established',shared_primary_ref:shared?.ref||null});}}
// Reconcile source-attested Hebrew/Aramaic aliases only with independent passage anchors.
const aliasGroups=new Map();for(const r of records.filter(r=>!removed.has(r.identity_key)))for(const a of r.aliases.filter(a=>a.language==='he'&&!a.search_only)){const n=norm(a.name);if(n.split(' ').filter(x=>!['רב','רבי','רבן','בן','בר','ר'].includes(x)).length<2)continue;const list=aliasGroups.get(n)||[];if(!list.includes(r))list.push(r);aliasGroups.set(n,list);}
for(const [alias,list] of aliasGroups)for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];if(removed.has(a.identity_key)||removed.has(b.identity_key)||!compatible(a,b))continue;if(numbered(a)&&numbered(b)&&a.identity_key!==b.identity_key)continue;if([a,b].some(r=>r.review_reasons.some(x=>/disambiguation page|Shared Wikipedia|Multiple Wikipedia persons|Several Sefaria/.test(x))))continue;const shared=a.primary_chazal_evidence.filter(anchored).find(e=>b.primary_chazal_evidence.some(f=>anchored(f)&&f.ref===e.ref));if(shared)merge(a,b,'Source-attested compound alias, independent common primary passage, compatible chronology; no number-only inference',{alias,common_primary_ref:shared.ref,alias_sources:[...a.aliases,...b.aliases].filter(x=>norm(x.name)===alias).map(x=>x.source)});}
records=records.filter(r=>!removed.has(r.identity_key));const byKey=new Map(records.map(r=>[r.identity_key,r]));const chase=k=>removed.has(k)?chase(removed.get(k)):k;
for(const d of read('identity-decisions.json').manual_review||[]){const r=byKey.get(chase(d.identity_key));if(r){r.review_reasons.push(d.reason);r.notes.push('Manual identity assessment sources: '+d.sources.join(' '));}}
for(const d of duplicates){d.identity_keys=[...new Set(d.identity_keys.map(chase))];if(d.identity_keys.length<2)continue;for(const k of d.identity_keys)byKey.get(k)?.review_reasons.push('Possible duplicate identity: '+d.identity_keys.filter(x=>x!==k).join(', '));}
const finalDuplicates=duplicates.filter(d=>d.identity_keys.length>1);
// Shared external identity identifiers are a conflict to inspect, not an invitation to silently collapse homonyms.
for(const field of ['wikidata','hewiki_pageid','bonayich']){const seen=new Map();for(const r of records){const id=r.external_ids[field];if(!id)continue;const old=seen.get(id);if(old&&old.identity_key!==r.identity_key){const d={identity_keys:[old.identity_key,r.identity_key],basis:'Shared '+field+' identifier',external_id:id};finalDuplicates.push(d);old.review_reasons.push('Shared external person identifier '+field+':'+id);r.review_reasons.push('Shared external person identifier '+field+':'+id);}else seen.set(id,r);}}
const master=[],review=[];
for(const r of records){if(r.classification)r.review_reasons=r.review_reasons.filter(x=>!x.startsWith('Reference identifies a person/contemporary'));if(r.external_ids.sefaria_slug||r.external_ids.hewiki_pageid){const informational=r.review_reasons.filter(x=>x.startsWith('Cross-reference-only Hyman')||x.startsWith('Same section marker'));r.notes.push(...informational);r.review_reasons=r.review_reasons.filter(x=>!informational.includes(x));}const classes=[...new Set(r.classification_assertions.map(x=>x.value))];if(classes.length>1)r.review_reasons.push('Conflicting Tanna/Amora identity assertions.');if(!r.classification)r.review_reasons.push('Tanna/Amora classification not established; do not infer from honorific or occurrence in the Talmud.');const support=r.primary_chazal_evidence.filter(anchored);r.candidate_primary_occurrences=r.primary_chazal_evidence.filter(e=>!anchored(e));r.primary_chazal_evidence=support;
 if(!support.length)r.review_reasons.push('No primary Chazal passage independently attributed to this identity was verified; lexical occurrences alone are insufficient.');
 if(r.birth_year!==null&&r.death_year!==null&&r.birth_year>r.death_year)r.review_reasons.push('Impossible chronology: asserted birth follows death.');
 r.review_reasons=[...new Set(r.review_reasons)];const kinds=new Set(r.secondary_identity_evidence.map(s=>s.kind));r.confidence=r.review_reasons.length?'manual_review':(kinds.has('hebrew_wikipedia')&&(kinds.has('hyman_1910_transcription')||kinds.has('sefaria_identity'))?'high':'medium');r.identity_status=r.confidence==='manual_review'?'needs_review':'resolved';r.lifecycle_status='research_only';r.knowledge_state=r.identity_status==='resolved'?'known':'disputed';
 r.aliases=[...new Map(r.aliases.map(x=>[x.language+':'+x.name,x])).values()];r.notes.push('Research census only; not integrated into the Toladot live database.');
 if(r.confidence==='manual_review')review.push(r);else master.push(r);
}
master.sort((a,b)=>(a.canonical_name_he||'').localeCompare(b.canonical_name_he||'','he'));review.sort((a,b)=>priority(a)-priority(b)||(a.canonical_name_he||'').localeCompare(b.canonical_name_he||'','he'));
for(const r of [...master,...review]){for(const field of ['teachers','students'])for(const rel of r[field])if(rel.target_identity_key){const k=chase(rel.target_identity_key);rel.target_identity_key=k;rel.target_person_id=byKey.get(k)?.person_id||null;}}
const counts={tannaim:master.filter(r=>r.classification==='Tanna').length,amoraim:master.filter(r=>r.classification==='Amora').length,amoraim_eretz_israel:master.filter(r=>r.classification==='Amora'&&r.region==='Eretz Israel').length,amoraim_babylonia:master.filter(r=>r.classification==='Amora'&&r.region==='Babylonia').length,amoraim_mixed_unknown:master.filter(r=>r.classification==='Amora'&&['mixed','unknown'].includes(r.region)).length,total_unique_sages:master.length,high_confidence_identities:master.filter(r=>r.confidence==='high').length,medium_confidence_identities:master.filter(r=>r.confidence==='medium').length,manual_review_candidate_records:review.length,suspected_duplicate_pairs:finalDuplicates.length,suspected_duplicate_candidate_records:new Set(finalDuplicates.flatMap(x=>x.identity_keys)).size,records_with_direct_primary_chazal_evidence:master.filter(r=>r.primary_chazal_evidence.length).length};
write('master-sages.json',{schema_version:'toladot-research-census-1',count_label:'The number of individually identifiable Tannaim and Amoraim found according to the Toladot methodology and processed source corpus.',scope:'All selected source corpus processed; conservative resolved subset, unresolved candidates excluded from unique-person counts.',counts,sages:master});write('manual-review-identities.json',{count_unit:'candidate records, NOT unique people',records:review});write('suspected-duplicates.json',{count_unit:'candidate pairs and records, NOT additional people',pairs:finalDuplicates});write('merge-audit.json',audit);write('counts.json',counts);console.log(JSON.stringify(counts,null,2));
