import fs from 'node:fs';import path from 'node:path';import {root,read,write,norm,clean,flatRef} from './lib.mjs';
const records=read('candidate-identities.json'),keyMap=read('identity-key-map.json'),byKey=new Map(records.map(r=>[r.identity_key,r]));
const manifest=read('corpus-manifest.json');const byRef=new Map(),coverage=[];
const secondaryOnly=/^(Darkhei HaTalmud|Introductions to |Mevo HaTalmud|Seder Olam Zutta|Sefer HaYashar|Midrash Lekach Tov|Midrash Sekhel Tov|Bereshit Rabbati|Ein Yaakov)/;
const lateCompilation=/^(Otzar Midrashim|Yalkut|Midrash Aggadah|Aggadat Bereshit)/;
const trie=new Map(),ambiguousAliases=new Map();
function insert(name,key,kind){const n=norm(name);if(n.length<4||!/[א-ת]/.test(n)||/^(רבי|רב|רבן|אבא|רבה|רבא|רבנן)$/.test(n))return;let node=trie;for(const w of n.split(' ')){if(!node.has(w))node.set(w,new Map());node=node.get(w);}if(!node.has('$'))node.set('$',[]);node.get('$').push({key,kind,name:n});}
for(const r of records)for(const a of r.aliases.filter(a=>a.language==='he'))insert(a.name,r.identity_key,'identity_alias');
for(const n of read('name-discovery-inventory.json'))insert(n.name,'name-inventory:'+n.id,'discovery_name');
const exclusions=read('identity-decisions.json').assignment_exclusions;
const refMentions=new Map();function addTagged(key,ref,text,source){const k=keyMap[key]||key;if(!byKey.has(k)||!ref||exclusions.some(e=>e.identity_key===k&&e.ref===ref))return;const list=refMentions.get(ref)||[];list.push({key:k,text,source});refMentions.set(ref,list);}
const wikiPointers=new Map();if(fs.existsSync(path.join(root,'wikipedia-primary-citation-pointers.json')))for(const c of read('wikipedia-primary-citation-pointers.json')){const r=records.find(r=>r.external_ids.hewiki_pageid===c.pageid);if(r){const a=wikiPointers.get(c.ref)||[];a.push({record:r,citation:c});wikiPointers.set(c.ref,a);}}
if(fs.existsSync(path.join(root,'hyman-primary-citation-pointers.json')))for(const c of read('hyman-primary-citation-pointers.json')){const r=byKey.get(c.identity_key);if(r){const a=wikiPointers.get(c.ref)||[];a.push({record:r,citation:{...c,template:c.original_reference,kind:'Hyman'}});wikiPointers.set(c.ref,a);}}
for(const book of ['bavli','mishnah','tosefta'])for(const x of read('raw/sperling_mentions_'+book+'.json')){if(x.id_matches.length!==1)continue;const id=x.id_matches[0];addTagged(id.startsWith('BONAYICH:')?'bonayich:'+id.split(':')[1]:'sefaria:'+id,x.ref,x.mention,'Sefaria-Data pretagged '+book);}
for(const r of records.filter(x=>x.external_ids.sefaria_slug)){const d=read('raw/topic-details/'+encodeURIComponent(r.external_ids.sefaria_slug)+'.json');for(const x of d.refs||[])for(const v of [x,...(x.similarRefs||[])]){if(v.is_sheet||v.linkType!=='mention'||!v.charLevelData)continue;if(v.charLevelData.language==='he')addTagged(r.identity_key,v.ref,v.charLevelData.text,'Sefaria topic Hebrew entity annotation');else addTagged(r.identity_key,v.ref,null,'Sefaria topic translated entity annotation; Hebrew alias must corroborate');}}
const hitsFile=fs.openSync(path.join(root,'corpus-mentions.jsonl'),'w');const discoveries=new Map();let totalSegments=0,totalHits=0,verifiedTagged=0;
function evidence(r,ref,raw,alias,method,book,key){if(exclusions.some(e=>e.identity_key===r.identity_key&&e.ref===ref)||r.primary_chazal_evidence.some(x=>x.ref===ref))return;if(r.primary_chazal_evidence.length>=40)return;const cleaned=clean(raw),at=norm(cleaned).indexOf(norm(alias||''));r.primary_chazal_evidence.push({ref,url:'https://www.sefaria.org/'+encodeURIComponent(ref.replaceAll(' ','_')),book:book.title,corpus:book.categories,export_source:book.cltk_flat_url,export_segment_key:key,mention:alias||null,excerpt:cleaned.length<=500?cleaned:cleaned.slice(Math.max(0,at-100),Math.max(0,at-100)+500),excerpt_is_normalized:true,identity_attribution:method,evidence_stratum:lateCompilation.test(book.title)?'later_compilation_of_traditions':'primary_corpus'});}
for(const book of manifest.books){if(book.status!=='downloaded')continue;const d=read('raw/corpus/'+book.key+'.json');let segs=0,hits=0;const isSecondary=secondaryOnly.test(book.title);for(const [key,raw] of Object.entries(d.text||{})){if(typeof raw!=='string'||!raw.trim())continue;segs++;const ref=flatRef(d,key);if(!ref)continue;const normalized=norm(raw),words=normalized.split(' ');byRef.set(ref,{book:book.title,key,normalized});const matched=[];
 for(let i=0;i<words.length;i++){let options=[words[i]];if(/^[ובכלמשד]/.test(words[i])&&words[i].length>2)options.push(words[i].slice(1));for(const start of options){let node=trie.get(start);if(!node)continue;for(let j=i;node&&j<Math.min(words.length,i+12);j++){if(node.has('$')){const values=[...new Map(node.get('$').map(x=>[x.key,x])).values()];const next=words[j+1];if(!['בן','בר','בריה','אבוה','בנו'].includes(next)){for(const v of values){matched.push(v);if(v.kind==='discovery_name'){const q=discoveries.get(v.key)||{key:v.key,name:v.name,count:0,refs:[]};q.count++;if(q.refs.length<8)q.refs.push({ref,source:book.cltk_flat_url,key});discoveries.set(v.key,q);}}}}node=node.get(words[j+1]);}}}
 const unique=[...new Map(matched.map(v=>[v.key+'|'+v.name,v])).values()];if(unique.length){hits+=unique.length;fs.writeSync(hitsFile,JSON.stringify({ref,book:book.title,key,secondary_only:isSecondary,matches:unique})+'\n');}
 if(isSecondary)continue;
 // Token matching generates candidate evidence. A shared name is never assigned to just one person.
 for(const v of unique.filter(x=>x.kind==='identity_alias')){const r=byKey.get(v.key);const owners=unique.filter(x=>x.kind==='identity_alias'&&x.name===v.name);evidence(r,ref,raw,v.name,owners.length===1?'unique_catalog_alias_occurrence_requires_identity_reference':'ambiguous_shared_alias',book,key);}
 for(const t of refMentions.get(ref)||[]){const r=byKey.get(t.key);const named=t.text?normalized.includes(norm(t.text)):r.aliases.some(a=>a.language==='he'&&norm(a.name).length>3&&normalized.includes(norm(a.name)));if(!named)continue;verifiedTagged++;const existing=r.primary_chazal_evidence.find(x=>x.ref===ref);if(existing){existing.identity_attribution=t.source;existing.mention=t.text||existing.mention;}else{if(r.primary_chazal_evidence.length>=40)r.primary_chazal_evidence.pop();evidence(r,ref,raw,t.text||r.aliases.find(a=>a.language==='he'&&norm(a.name).length>3&&normalized.includes(norm(a.name)))?.name||r.canonical_name_he,t.source,book,key);}}
 for(const pref of [ref,ref.replace(/:[^:]+$/,''),ref.split(':')[0]])for(const {record:r,citation:c} of wikiPointers.get(pref)||[]){const aliases=r.aliases.filter(a=>a.language==='he').map(a=>norm(a.name.replace(/\([^)]*\)/g,''))).filter(a=>a.length>3);const name=aliases.find(a=>normalized.includes(a));if(!name)continue;let existing=r.primary_chazal_evidence.find(x=>x.ref===ref);const method=(c.kind||'Wikipedia')+' citation plus Hebrew subject-name occurrence';if(!existing){if(r.primary_chazal_evidence.length>=40)r.primary_chazal_evidence.pop();evidence(r,ref,raw,name,method,book,key);existing=r.primary_chazal_evidence.find(x=>x.ref===ref);}if(existing){existing.identity_attribution=method;existing.secondary_identity_anchor=c.source;existing.secondary_citation_template=c.template;}}
 }coverage.push({title:book.title,categories:book.categories,segments_scanned:segs,alias_hits:hits,secondary_only:isSecondary,later_compilation:lateCompilation.test(book.title),status:'scanned'});totalSegments+=segs;totalHits+=hits;if(coverage.length%30===0)console.log('scanned',coverage.length,'segments',totalSegments);}
fs.closeSync(hitsFile);write('scanned-identities.json',records);write('discovered-name-occurrences.json',[...discoveries.values()]);write('scan-coverage.json',{books:coverage,total_segments:totalSegments,total_alias_hits:totalHits,verified_tagged_occurrences:verifiedTagged,ref_generation:'Sefaria cltk-flat zero-based counters converted using meta; source keys retained for audit.'});console.log('scan complete',totalSegments,totalHits,verifiedTagged);
