import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';
const root=path.dirname(fileURLToPath(import.meta.url)),dir=path.join(root,'raw/wiki');fs.mkdirSync(dir,{recursive:true});
async function api(params){const u='https://he.wikipedia.org/w/api.php?'+new URLSearchParams({format:'json',...params});const cache=path.join(root,'raw','wiki-request-'+crypto.createHash('sha256').update(u).digest('hex').slice(0,16)+'.json');if(fs.existsSync(cache))return JSON.parse(fs.readFileSync(cache));for(let i=0;i<8;i++){try{await new Promise(r=>setTimeout(r,2500));const r=await fetch(u,{headers:{'User-Agent':'ToladotCensus/1.0 research'},signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d.error)throw Error(JSON.stringify(d.error));fs.writeFileSync(cache,JSON.stringify(d));return d;}catch(e){if(i===7)throw e;console.log('retry',params.cmtitle||params.titles?.slice(0,40),String(e));await new Promise(r=>setTimeout(r,30000*(i+1)));}}}
const queue=['קטגוריה:תנאים','קטגוריה:אמוראים'],visited=new Set(),pages=new Map(),cats=[];
while(queue.length){const title=queue.shift();if(visited.has(title))continue;visited.add(title);let cont={};do{const d=await api({action:'query',list:'categorymembers',cmtitle:title,cmlimit:500,...cont});cats.push({title,response:d});for(const x of d.query.categorymembers){if(x.ns===14&&/תנאי|תנאים|אמורא|הזוגות|נחותי/.test(x.title)&&!/^קטגוריה:תלמידי רבנים/.test(x.title))queue.push(x.title);if(x.ns===0){const row=pages.get(x.pageid)||{...x,categories:[]};row.categories.push(title);pages.set(x.pageid,row);}}cont=d.continue||{};}while(cont.cmcontinue);console.log(title,pages.size);}
const topics=JSON.parse(fs.readFileSync(path.join(root,'raw/topics.json')));const extra=topics.filter(t=>t.subclass==='person'&&t.properties?.heWikiLink?.value).map(t=>decodeURIComponent(t.properties.heWikiLink.value.split('/wiki/')[1]||'').replaceAll('_',' ')).filter(Boolean);
fs.writeFileSync(path.join(root,'wiki-category-manifest.json'),JSON.stringify({categories:cats,pages:[...pages.values()],extra_titles:extra},null,2));
const titles=[...new Set([...pages.values()].map(x=>x.title).concat(extra))];const jobs=[];for(let i=0;i<titles.length;i+=20)jobs.push(titles.slice(i,i+20));let done=0;
async function worker(){while(jobs.length){const batch=jobs.shift();const key=batch[0].replaceAll(/[<>:"/\\|?*]/g,'_');const dest=path.join(dir,key+'.json');if(!fs.existsSync(dest)){try{const d=await api({action:'query',prop:'revisions|pageprops|categories',rvprop:'ids|timestamp|content',rvslots:'main',ppprop:'wikibase_item|disambiguation',cllimit:500,redirects:1,titles:batch.join('|')});fs.writeFileSync(dest,JSON.stringify(d));}catch(e){console.log('failed',batch,String(e));}}done+=batch.length;console.log('wiki pages',done,'/',titles.length);}}
await worker();
const ids=new Set();for(const f of fs.readdirSync(dir)){const d=JSON.parse(fs.readFileSync(path.join(dir,f)));for(const p of Object.values(d.query?.pages||{}))if(p.pageprops?.wikibase_item)ids.add(p.pageprops.wikibase_item);}
fs.mkdirSync(path.join(root,'raw/wikidata'),{recursive:true});const q=[...ids];for(let i=0;i<q.length;i+=50){const batch=q.slice(i,i+50),dest=path.join(root,'raw/wikidata',batch[0]+'.json');if(fs.existsSync(dest))continue;for(let attempt=0;attempt<8;attempt++){await new Promise(r=>setTimeout(r,15000));try{const url='https://www.wikidata.org/w/api.php?'+new URLSearchParams({action:'wbgetentities',ids:batch.join('|'),props:'labels|aliases|claims|sitelinks',languages:'he|en',format:'json'});const r=await fetch(url,{signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(data.error)throw Error(JSON.stringify(data.error));fs.writeFileSync(dest,JSON.stringify(data));console.log('wikidata',i+batch.length,'/',q.length);break;}catch(e){console.log('wikidata retry',attempt,String(e));if(attempt===7)throw e;await new Promise(r=>setTimeout(r,60000));}}}
