import {afterEach,describe,expect,it} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import KnowledgeGraph from '@/components/knowledge/KnowledgeGraph';
import {hierarchy} from '@/components/knowledge/hierarchy';
import data from '@/components/knowledge/pilot.json';
afterEach(cleanup);
describe('knowledge hierarchy',()=>{
 it('retains every person when relationship filters change',()=>{const {container}=render(<KnowledgeGraph/>);for(const family of ['all','teacher_student','parent_child','spouse','sibling','bar_plugta']){fireEvent.change(screen.getByLabelText('סוג קשר'),{target:{value:family}});expect(container.querySelectorAll('[data-node]')).toHaveLength(data.people.length);}});
 it('places dated teachers above their students in the pilot',()=>{const {positions}=hierarchy(data.people,data.edges);for(const e of data.edges.filter(e=>e.family==='teacher_student')){const a=positions.get(e.a)!,b=positions.get(e.b)!;if(a.rank!==null&&b.rank!==null)expect(a.y,`${e.a} -> ${e.b}`).toBeLessThan(b.y);}});
 it('preserves the full Avot chain including BOTH recipients of BOTH teachers',()=>{const layers=[['shimon-tzadik'],['antigonos'],['yose-yoezer','yose-yochanan'],['yehoshua-perachya','nittai'],['yehuda-tabbai','shimon-shetach'],['shemaya','avtalyon'],['hillel','shammai']];const person=(slug:string)=>data.people.find(p=>p.slug===slug)!;const {positions}=hierarchy(data.people,data.edges);for(let i=1;i<layers.length;i++)for(const a of layers[i-1]!)for(const b of layers[i]!){expect(data.edges.some(e=>e.family==='teacher_student'&&e.a===person(a).id&&e.b===person(b).id),`${a} -> ${b}`).toBe(true);expect(positions.get(person(a).id)!.y).toBeLessThan(positions.get(person(b).id)!.y);}expect(positions.get(person('shemaya').id)!.y).toBe(positions.get(person('avtalyon').id)!.y);});
 it('does not move a later sage to the first generation when relationships are missing',()=>{const p=[{id:'old',name:'old',chronology:{order:0,label:'earlier',period_id:'early'}},{id:'later',name:'later',chronology:{order:5,label:'later',period_id:'late'}}];const result=hierarchy(p,[]);expect(result.positions.get('later')!.y).toBeGreaterThan(result.positions.get('old')!.y);expect(result.unplaced).toEqual([]);});
 it('places Akavya alongside Hillel and Shammai without inventing a teaching edge',()=>{const {positions}=hierarchy(data.people,data.edges);const ids=['akavya','hillel','shammai'].map(slug=>data.people.find(p=>p.slug===slug)!.id);expect(new Set(ids.map(id=>positions.get(id)!.y)).size).toBe(1);render(<KnowledgeGraph/>);expect(screen.getByRole('button',{name:'עקביא בן מהללאל'})).toBeInTheDocument();expect(data.edges.some(e=>e.family==='teacher_student'&&(e.a===ids[0]||e.b===ids[0]))).toBe(false);});
 it('scrolls vertically with the wheel and reserves zoom for buttons',()=>{const {container}=render(<KnowledgeGraph/>);const svg=screen.getByLabelText('מפת קשרים אינטראקטיבית; אפשר לבחור חכם גם ברשימה');const transform=()=>container.querySelector('svg > g')!.getAttribute('transform');const before=transform();fireEvent.wheel(svg,{deltaY:120});expect(transform()).not.toBe(before);expect(transform()).toContain('scale(1)');fireEvent.click(screen.getByRole('button',{name:'התקרבות'}));expect(transform()).toContain('scale(1.25)');});
 it('enters full window mode and restores scrolling on Escape',()=>{const {container}=render(<KnowledgeGraph/>);const original=document.body.style.overflow;fireEvent.click(screen.getByRole('button',{name:'מסך מלא ⛶'}));expect(container.querySelector('.kg-fullscreen')).toBeInTheDocument();expect(document.body.style.overflow).toBe('hidden');fireEvent.keyDown(window,{key:'Escape'});expect(container.querySelector('.kg-fullscreen')).not.toBeInTheDocument();expect(document.body.style.overflow).toBe(original);});
 it('separates teachers and students independently of canvas filtering',()=>{render(<KnowledgeGraph/>);fireEvent.change(screen.getByLabelText('סוג קשר'),{target:{value:'spouse'}});fireEvent.click(screen.getByRole('button',{name:'רבי עקיבא'}));expect(screen.getByRole('heading',{name:'רבותיו'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'תלמידיו'})).toBeInTheDocument();const card=screen.getByLabelText('כרטיס חכם ומקורות');expect(card).toHaveTextContent('רבי אליעזר בן הורקנוס');expect(card).toHaveTextContent('רבי מאיר');expect(screen.getByRole('heading',{name:'מקורות להרחבה'})).toBeInTheDocument();});
 it('does not assign a fabricated transmission level to disconnected or cyclic records',()=>{const p=['a','b','c'].map(id=>({id,name:id}));const result=hierarchy(p,[{a:'a',b:'b',family:'teacher_student'},{a:'b',b:'a',family:'teacher_student'}]);expect(result.unplaced.sort()).toEqual(['a','b','c']);});
 it('allows selection to be cleared by background click and Escape',()=>{render(<KnowledgeGraph/>);const akiva=screen.getByRole('button',{name:'רבי עקיבא'});fireEvent.click(akiva);expect(screen.getByLabelText('כרטיס חכם ומקורות')).toBeInTheDocument();const svg=screen.getByLabelText('מפת קשרים אינטראקטיבית; אפשר לבחור חכם גם ברשימה');fireEvent.pointerDown(svg,{pointerId:1,clientX:20,clientY:20});fireEvent.pointerUp(svg,{pointerId:1,clientX:20,clientY:20});expect(screen.queryByLabelText('כרטיס חכם ומקורות')).not.toBeInTheDocument();fireEvent.click(akiva);fireEvent.keyDown(window,{key:'Escape'});expect(screen.queryByLabelText('כרטיס חכם ומקורות')).not.toBeInTheDocument();});
 it('has no persistent person list and exposes floating close control',()=>{render(<KnowledgeGraph/>);expect(screen.queryByLabelText('תוצאות חיפוש')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'רבי עקיבא'}));fireEvent.click(screen.getByRole('button',{name:'סגירת החלונית'}));expect(screen.queryByLabelText('כרטיס חכם ומקורות')).not.toBeInTheDocument();});
});

